[build]
  command = "npm run build"
  functions = "functions"
  public = "dist"

  [dev]
    framework = "#custom"
    command = "npm run dev:webpack"
    targetPort = 8079
    port = 8080
    public = "dist"
    autoLaunch = true